(()=>{
const $=id=>document.getElementById(id),cfg=window.DURAK_SUPABASE||{},ready=!!(cfg.url&&cfg.publishableKey&&window.supabase),client=ready?window.supabase.createClient(cfg.url,cfg.publishableKey):null;
let session=null,profile=null,register=false;
const countries={MD:"Republica Moldova",RO:"România",IT:"Italia",UA:"Ucraina",DE:"Germania",GB:"Regatul Unit",US:"Statele Unite",OTHER:"Altă țară"};
const LOCAL_USERS="durak_test_users_v1",LOCAL_SESSION="durak_test_session_v1";
const bytesToHex=b=>Array.from(new Uint8Array(b),x=>x.toString(16).padStart(2,"0")).join("");
const randomHex=n=>{let b=new Uint8Array(n);crypto.getRandomValues(b);return bytesToHex(b)};
async function localHash(password,salt){let key=await crypto.subtle.importKey("raw",new TextEncoder().encode(password),"PBKDF2",false,["deriveBits"]),bits=await crypto.subtle.deriveBits({name:"PBKDF2",salt:new TextEncoder().encode(salt),iterations:150000,hash:"SHA-256"},key,256);return bytesToHex(bits)}
const localUsers=()=>{try{return JSON.parse(localStorage.getItem(LOCAL_USERS))||[]}catch{return[]}};
function detectedCountry(){let zone="",locale="";try{zone=Intl.DateTimeFormat().resolvedOptions().timeZone||"";locale=navigator.language||""}catch{}let zones={"Europe/Rome":"IT","Europe/Vatican":"IT","Europe/San_Marino":"IT","Europe/Bucharest":"RO","Europe/Chisinau":"MD","Europe/Kiev":"UA","Europe/Kyiv":"UA","Europe/Berlin":"DE","Europe/London":"GB"};if(zones[zone])return zones[zone];let region=locale.match(/[-_]([A-Z]{2})$/i)?.[1]?.toUpperCase();return countries[region]?region:"OTHER"}
function applyDetectedCountry(){let detected=detectedCountry();if($("authCountry")&&detected!=="OTHER")$("authCountry").value=detected;if(ready||detected==="OTHER")return;let id=localStorage.getItem(LOCAL_SESSION),users=localUsers(),user=users.find(u=>u.id===id);if(!user||user.country===detected)return;user.country=detected;localStorage.setItem(LOCAL_USERS,JSON.stringify(users));if(session?.user?.id===user.id){profile.country=detected;draw()}}
function saveLocalSession(user){if(user)localStorage.setItem(LOCAL_SESSION,user.id);else localStorage.removeItem(LOCAL_SESSION);session=user?{user:{id:user.id,email:user.email}}:null;profile=user?{username:user.username,country:user.country,level:1,wins:0,losses:0}:null;draw()}
function message(text,bad=false){$("authMessage").textContent=text;$("authMessage").className=`network-status ${bad?"error":"ok"}`}
function draw(){let logged=!!session?.user;$("accountLabel").textContent=logged?`${profile?.username||"Jucător"} · ${countries[profile?.country]||profile?.country||""}`:"Nu ești autentificat";$("accountBtn").hidden=logged;$("logoutBtn").hidden=!logged;if(logged){$("authModal").hidden=true;if(!$("setup").hidden||!$("onlineLobby").hidden)return;$("mainMenu").hidden=false;if(profile?.username)$("onlineName").value=profile.username}else{$("authModal").hidden=false;$("mainMenu").hidden=true;$("setup").hidden=true;$("onlineLobby").hidden=true;$("modal").hidden=true;mode(false);showAuth()}}
function showAuth(){$("authModal").hidden=false;$("authSubmit").disabled=false;$("authSwitch").hidden=false;$("forgotPassword").hidden=!ready;message(ready?"":"MOD TEST LOCAL — contul rămâne numai în acest browser.")}
function mode(isRegister){register=isRegister;$("registerFields").hidden=!register;$("authTitle").textContent=register?"Creează cont":"Intră în cont";$("authSubmit").textContent=register?"Înregistrează-te":"Intră";$("authSwitch").textContent=register?"Ai deja cont? Intră":"Nu ai cont? Înregistrează-te";$("authPassword").autocomplete=register?"new-password":"current-password"}
async function loadProfile(){if(!session?.user){window.DurakProfile?.disconnectCloud?.();return profile=null}let {data}=await client.from("profiles").select("username,country,level,wins,losses").eq("id",session.user.id).maybeSingle();profile=data;window.DurakProfile?.connectCloud?.(client,session.user.id,profile?.username);await window.DurakProfile?.pullCloudProfile?.();draw()}
async function submit(){let email=$("authEmail").value.trim().toLowerCase(),password=$("authPassword").value;if(!email||password.length<8)return message("Completează emailul și o parolă de minimum 8 caractere.",true);$("authSubmit").disabled=true;try{if(!ready){let users=localUsers();if(register){let username=$("authName").value.trim(),country=$("authCountry").value;if(username.length<3)throw Error("Numele trebuie să aibă cel puțin 3 caractere.");if(users.some(u=>u.email===email))throw Error("Există deja un cont cu acest email.");let salt=randomHex(16),user={id:crypto.randomUUID(),email,username,country,salt,passwordHash:await localHash(password,salt)};users.push(user);localStorage.setItem(LOCAL_USERS,JSON.stringify(users));saveLocalSession(user)}else{let user=users.find(u=>u.email===email);if(!user||user.passwordHash!==await localHash(password,user.salt))throw Error("Email sau parolă incorectă.");saveLocalSession(user)}return}if(register){let username=$("authName").value.trim(),country=$("authCountry").value;if(username.length<3)throw Error("Numele trebuie să aibă cel puțin 3 caractere.");let {error}=await client.auth.signUp({email,password,options:{data:{username,country},emailRedirectTo:location.origin}});if(error)throw error;message("Cont creat. Verifică emailul pentru confirmare.")}else{let {error}=await client.auth.signInWithPassword({email,password});if(error)throw error;$("authModal").hidden=true}}catch(e){message(e.message||"Nu s-a putut continua.",true)}finally{$("authSubmit").disabled=false}}
async function requireAccount(){if(session?.user)return true;showAuth();message("Ai nevoie de un cont confirmat pentru mesele publice.",true);return false}
async function listRooms(){if(!await requireAccount())return[];if(!client)throw Error("Mesele publice necesită baza de date Supabase.");let {data,error}=await client.from("public_rooms").select("id,code,name,players,max_players,status,created_at").eq("status","waiting").order("created_at",{ascending:false}).limit(30);if(error)throw error;return data||[]}
async function createRoom(code,name,maxPlayers=6){if(!await requireAccount())throw Error("Autentificare necesară");if(!client)throw Error("Mesele publice necesită baza de date Supabase.");let {data,error}=await client.from("public_rooms").insert({code,name,max_players:maxPlayers,host_id:session.user.id}).select().single();if(error)throw error;return data}
async function joinRoom(id){if(!await requireAccount())throw Error("Autentificare necesară");if(!client)throw Error("Mesele publice necesită baza de date Supabase.");let {data,error}=await client.rpc("join_public_room",{p_room_id:id});if(error)throw error;return data}
async function closeRoom(code,status="closed"){if(!client||!session)return;await client.from("public_rooms").update({status}).eq("code",code).eq("host_id",session.user.id)}
$("accountBtn").onclick=showAuth;$("authSwitch").onclick=()=>mode(!register);$("authSubmit").onclick=submit;$("logoutBtn").onclick=()=>client?client.auth.signOut():saveLocalSession(null);$("forgotPassword").onclick=async()=>{let email=$("authEmail").value.trim();if(!email)return message("Scrie întâi adresa de email.",true);let {error}=await client.auth.resetPasswordForEmail(email,{redirectTo:location.origin});message(error?error.message:"Am trimis linkul de recuperare.",!!error)};
window.DurakAuth={ready,client,get session(){return session},get profile(){return profile},requireAccount,listRooms,createRoom,joinRoom,closeRoom,showAuth};
if(client){applyDetectedCountry();client.auth.getSession().then(({data})=>{session=data.session;loadProfile()});client.auth.onAuthStateChange((_e,s)=>{session=s;loadProfile()})}else{let id=localStorage.getItem(LOCAL_SESSION),user=localUsers().find(u=>u.id===id);if(user)saveLocalSession(user);else draw();applyDetectedCountry()}
})();
