const SUITS=["♠","♥","♦","♣"],RANKS=["6","7","8","9","10","J","Q","K","A"];
const NAMES=["Boris","Dmitri","Nikolai","Sasha","Viktor","Ivan","Misha","Yuri","Alexei","Grigori","Andrei","Maksim","Pavel","Sergei","Vladimir","Kirill","Roman","Oleg","Artyom","Denis","Vadim","Igor","Evgeni","Ruslan","Timur","Leonid","Fiodor","Ghenadi","Valeri","Stanislav","Ilya","Konstantin","Anatoli","Vasili","Makar","Rodion"];
const LINES={
 think:["Ia să chitesc oleacă…","Unde-i asul cela, blea?","Iaca, poate asta…","Șăzi blând, am un plan!","Măi, ce boroboață…","Stai hăi, nu mă mâna!","Amuș găsesc eu ceva.","Davai, cărților, lucrați!","Ian să vedem ce hal de mână am.","Parcă-s cu ochii-n păpușoi…","Asta-i carte ori ștergar?","Mă scarpin la bostan și aleg.","Nu mă grăbi, că-mi sare țandăra.","Of, parcă aleg harbuz din grădină.","Hai, măi, una trebuie să fie bună!"],
 attack:["Na, apără asta!","Iaca poznă pentru tine!","Nu te hlizi, că mai am!","Amu să te văd!","Ține-o pe asta, măi omule!","Davai, bate-o dacă poți!","Na-ți-o, că-i caldă!","Ia de-aici și nu cârti!","Am zvârlit-o, descurcă-te!","Asta vine ca rata prin păpușoi!","Hopa, ți-am pus-o pe masă!","Hai, nu te face că plouă.","Să vedem ce hram porți, măi!","Ține bine, că mai vine una!","Na, beleaua vine singură!","Ia cartea, că nu-i mămăligă!","Amu ori te aperi, ori strângi masa.","Să nu zici că nu te-am prevenit!"],
 take:["M-ai zăibit cu cărțile estea!","Ei, am sfeclit-o…","Tulai, iar le iau eu?","Oleacă de noroc n-ar strica.","Asta-i belea, nu joacă!","Pizdet, mi s-a dus tot planul!","Blea, iar strâng cărțile ca găinile!","Ei, dă-le-n păpușoi, le iau.","M-am pricopsit ca prostul satului.","Frumos, mi-ai pus sacul în spinare.","Să-mi trag una, ce mână proastă!","Aista-i noroc cu fundul în sus.","Of, le duc acasă cu căruța.","M-ai făcut de cacao, bre.","Ei, lasă că se întoarce roata!","Mânca-v-ar cioara de cărți!","Ce dracu', toate vin la mine?","Parcă-s poștaș, le adun pe toate."],
 win:["Ei, cine-i Durak amu?","Victorie, măi fraților!","Iaca așa se joacă la noi!","Davai muzica, am câștigat!","Hă-hă, v-am dus cu preșul!","Am făcut treabă, nu borș!","Să vadă tot satul cine-i gospodar!","Iaca, nu degeaba am mâncat mămăligă!","V-am aranjat ca pe lemne în șopron!","Amu puteți să vă hliziți.","Gata, puneți samovarul la foc!","Câștigător, fără cumătrie!"],
 angry:["M-ai zăibit, măi!","Ei, asta-i boroboață!","Nu-i bună treaba deloc!","Blea, ce carte de-a oaia!","Măi, îmi vine să răstorn masa!","Du-te-n păpușoi cu norocul tău!","Pizdet, iar m-ai prins!","Nu te hlizi, că mă enervez!","Aista-i furt pe față, bre!","Să-mi trag una, ce ghinion!","Măi drace, de unde ai scos-o?","Amu chiar că mi-a sărit muștarul!","Fir-ar ea de carte șchioapă!","Stai că-ți arăt eu cum latră câinele!","Ei, lasă, nu-i nunta ta încă!"],
 laugh:["Hă-hă! Iaca poznă!","Ei, te-am prins, măi!","Apoi asta-i bună!","Hăi, că m-ai făcut să râd!","Te-ai încurcat ca vițelul în funie!","Iaca boroboața de pe masă!","Hă-hă, ai dat cu bâta-n baltă!","Măi, ce comedie de carte!","Asta da, circ fără bilet!","Te-ai pornit la târg fără bani!","Hopa, ți s-a rupt căruța!","Ei, amu cine se hlizește?","Ai nimerit ca nuca-n perete!","Hă-hă, bună treabă… pentru mine!","Te-am prins cu mâța-n sac, bre!"]
};
const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms)),READ_TIME=3000;
let deck=[],players=[],trumpSuit,battle=[],attacker=0,defender=1,attackLimit=6,turn="idle",over=false,botAmount=3,finishOrder=[],moveHistory=[],singleGameId="",attackBatchTimer=null,humanReactionTimer=null,openingRun=0,lastBotDialogueAt=-Infinity;
const ATTACK_BATCH_MS=1100,BOT_DIALOG_CHANCE=.28,BOT_DIALOG_COOLDOWN_MS=14000;
const pick=a=>a[Math.floor(Math.random()*a.length)],strength=c=>RANKS.indexOf(c.rank)+(c.suit===trumpSuit?20:0);
const VILLAGE={
 starts:["Iaca","Amu","Măi omule","Hăi bre","Ei comedie","Tulai Doamne","Blea","Davai","Ian uite","Apoi","Măi drace","Of, lume","Ei na","Hopa","Auzi colo"],
 people:["cumătre","măi băiete","vecine","gospodarule","măi nene","flăcăule","măi om bun","bre","măi frate","căpitane de șură"],
 things:["păpușoi","barabule","harbuz","mămăligă","bostan","căruță","coteț","șopron","ceaun","samovar","opincă","coasă","greblă","sac de făină","gardul vecinului","găina din ogradă"],
 trouble:["am sfeclit-o","m-ai zăibit","mi-a sărit muștarul","s-a dus planul pe copcă","m-am pricopsit","asta-i belea","m-ai prins cu mâța-n sac","mi-ai pus capac","s-a rupt căruța","mi-ai făcut-o coaptă","nu-i a bună","m-ai băgat în bortă"],
 verbs:["te-ai încurcat","ai nimerit","te-ai pornit","ai zvârlit-o","te-ai proțăpit","ai dat-o","te-ai trezit","ai venit","te-ai lipit","te-ai tupilat"],
 comparisons:["ca vițelul în funie","ca nuca-n perete","ca rata prin păpușoi","ca găina la barieră","ca musca-n smântână","ca mirele fără nuntă","ca baba la internet","ca tractorul fără motor","ca ploaia la hram","ca barabula-n borș","ca motanul în pod","ca roata-n glod"],
 threats:["îți pun cartea-n poală","te trimit după barabule","îți umplu mâna","îți stric tot hramul","te las cu sacul plin","îți dau de lucru până mâine","te fac gospodar de cărți","îți trimit norocul la păscut","îți pun beleaua pe masă","te las să numeri până la Paște"],
 praise:["asta-i treabă gospodărească","a mers ca unsă","iaca joc cu cap","asta da poznă","am nimerit-o la țanc","merge treaba ca la hram","am făcut-o lată și frumoasă","asta-i carte cu obraz","am pus-o bine, bre","parcă mi-a șoptit baba"],
 swear:["fir-ar să fie","pizdet de noroc","ce dracu' de carte","dă-o-n păpușoi","să-mi trag una","blea, nu iar","mânca-v-ar cioara","bat-o s-o bată","lua-o-ar glodul","du-te-n bostan"],
 slangThink:["Și buksuiești?","Și ai zdviguri?","Și s-o slucit cu tini?","Tu ai clikuha?","Tu ai svet acasă?","Trudnîi, bre…","Șini-i nacialinic pi zdania asta?","Tu auzi și eu ție îți vtiresc aiși?","Șel mai ghenii, ia chitește.","Tormozești aiși?","Aha.","Ladna, pohui.","A pentru shi?"],
 slangAttack:["Și vrei bazar cu strelkî?","Și crez că ești pup zemli?","Și ești așa de derzkii?","Trebu să te zdarovești cu pațanii!","Tu ganești ori joci?","Și naejăști? Na cartea!","Tormozești aiși, amu atac eu!","Tăt o să șie clasna!","Tu ești puteovîi? Apără!","Și blea, ț-o ahuit cabina?","Kiss my ass!","Du-te nahui!","Hai, te rog frumos, nu te prea agita.","Pohui + poebati!"],
 slangAngry:["Și blea, ț-o ahuit cabina?","Și ganești?","Și naejăști la mine?","M-ai făcut șleambur, bre!","Asta-i ștampovki, nu noroc!","Ce stuțîr de mână am!","Șini ne peredal za praezd?","Tu ganghești, eu pierd!","Trudnîi joc, blea!","Tăt îi colina, numai la mine nu!","Pohui nahui!","Suka ebanaia!","Loh!","Du-te nahui!","Ladna, pohui."],
 slangLaugh:["Știi și de krasivo? Am afighit!","Șel mai ghenii, hă-hă!","Tu ești puteovîi, bre!","Tăt o să șie clasna!","Și crez că ești pup zemli?","Tu ai clikuha de Durak?","Șnuroc de noroc ai!","Șibionkî pe masă, hă-hă!","Tăt îi colina la mine!","Ține o pazdravlenie și de la mine!","Ahahahhaha!","Loh!","Aha!","Kiss my ass!","Hai, te rog frumos, nu te prea agita!"]
};
function villageLine(kind){let v=VILLAGE,s=pick(v.starts),p=pick(v.people);if(Math.random()<.48){if(kind==="think")return pick(v.slangThink);if(kind==="attack")return pick(v.slangAttack);if(kind==="take"||kind==="angry")return pick(v.slangAngry);if(kind==="laugh")return pick(v.slangLaugh)}if(kind==="think")return pick([`${s}, să chitesc oleacă, ${p}.`,`${s}, cartea asta stă ${pick(v.comparisons)}.`,`${pick(v.swear)}, unde mi-i norocul?`,`${s}, aleg de parcă aleg ${pick(v.things)} la târg.`]);if(kind==="attack")return pick([`${s}, ${p}, ${pick(v.threats)}!`,`${s}, na-ți-o ${pick(v.comparisons)}!`,`${pick(v.praise)} — amu apără!`,`${p}, ${pick(v.verbs)} ${pick(v.comparisons)}!`]);if(kind==="take"||kind==="angry")return pick([`${s}, ${pick(v.trouble)}!`,`${pick(v.swear)}, ${p}!`,`${s}, iar adun cărți ca ${pick(v.things)}!`,`${p}, ${pick(v.trouble)}, ${pick(v.swear)}!`]);if(kind==="laugh")return pick([`Hă-hă, ${p}, ${pick(v.verbs)} ${pick(v.comparisons)}!`,`${s}! ${pick(v.praise)}!`,`${p}, te-ai făcut de râs lângă ${pick(v.things)}!`,`${s}, asta-i comedie de la hram!`]);return `${s}, ${pick(v.praise)}!`}
function say(kind){return window.DurakMoldovanVocabulary.say(kind)}
function maybeBotLine(kind,preferred=""){let now=Date.now();if(now-lastBotDialogueAt<BOT_DIALOG_COOLDOWN_MS||Math.random()>=BOT_DIALOG_CHANCE)return "";lastBotDialogueAt=now;return preferred||say(kind)}
function botMood(i,type,kind,preferred=""){let line=maybeBotLine(kind,preferred);mood(i,`${type}${line?" talking":""}`,line);return line}
const beats=(d,a)=>(d.suit===a.suit&&strength(d)>strength(a))||(d.suit===trumpSuit&&a.suit!==trumpSuit);
const makeDeck=()=>SUITS.flatMap(s=>RANKS.map(r=>({suit:s,rank:r,id:s+r+Math.random()}))).sort(()=>Math.random()-.5);
const active=()=>players.filter(p=>!p.out),nextActive=i=>{for(let n=1;n<=players.length;n++){let j=(i+n)%players.length;if(!players[j].out)return j}return i};
function avatarHTML(p){let kind=p.openingEmotion==="angry"?"angry":p.openingEmotion==="laughing"?"laugh":"think",line=p.forceDialogue?p.openingLine:p.human?"":p.openingLine?maybeBotLine(kind,p.openingLine):"";return `<div class="bot-avatar ${p.hairStyle} ${p.eyeStyle} ${p.facialHair} ${p.openingEmotion||""} ${line?"talking":""}" id="avatar-${p.id}" style="--shirt:${p.shirt};--hair:${p.hair};--skin:${p.skin}"><div class="accessory ${p.accessory||"none"}"></div><div class="hair"></div><div class="face"><div class="brow left"></div><div class="brow right"></div><div class="eye left"><i></i></div><div class="eye right"><i></i></div><div class="nose"></div><div class="mouth"></div><div class="facial-hair"></div><div class="tattoo ${p.tattoo}">${p.tattoo==="none"?"":pick(["★","⚡","龍","♠"])}</div></div><div class="shoulders ${p.outfit}" style="${window.DurakAvatarArrival.outfitStyle(p.outfit)}"></div>${window.DurakAvatarArrival.walkingBodyHTML()}<div class="thought">${line||"Hmm…"}</div></div>`}
function cardHTML(c,cls=""){let red=c.suit==="♥"||c.suit==="♦",drag=cls.includes("player-card")?' draggable="true" title="Ține apăsat și trage cartea pe masă"':"";return `<div class="card ${red?"red":""} ${cls}" data-id="${c.id}"${drag}><span class="corner">${c.rank}<br>${c.suit}</span>${c.suit}<span class="corner bottom">${c.rank}<br>${c.suit}</span></div>`}
function botCardHTML(){return `<div class="card back"></div>`}
function mood(i,type,text=""){let a=$(`#avatar-${i}`);if(!a)return;if(type.includes("happy"))type=type.replace("happy","laughing");if(type.includes("worried")){let emotion=players[i]?.hand.length>=5?"angry":pick(["angry","sad","panic"]);type=type.replace("worried",emotion)}if(!text)type=type.replace(/\btalking\b/g,"");let p=players[i];a.className=`bot-avatar ${p.hairStyle||""} ${p.eyeStyle||""} ${p.facialHair||""} ${type}`;a.querySelector(".thought").textContent=text;let h=$(`#hand-${i}`);if(h)h.classList.toggle("peek",type.includes("thinking"))}
function humanPlayableCardIds(){let p=players[0];if(!p||p.out||over)return null;if(turn==="humanAttack")return new Set(battle.length<attackLimit?p.hand.filter(c=>!battle.length||c.rank===battle[0].attack.rank).map(c=>c.id):[]);if(turn==="humanAttackBatch")return new Set(battle.length<attackLimit?p.hand.filter(c=>c.rank===battle[0]?.attack.rank).map(c=>c.id):[]);if(turn==="humanAdd"||turn==="humanAddBatch"||turn==="humanAddTaking"){let ranks=new Set(battle.flatMap(x=>[x.attack.rank,x.defense?.rank].filter(Boolean)));return new Set(battle.length<attackLimit?p.hand.filter(c=>ranks.has(c.rank)).map(c=>c.id):[])}if(turn==="humanDefend"){let open=battle.find(x=>!x.defense);return new Set(open?p.hand.filter(c=>beats(c,open.attack)).map(c=>c.id):[])}return null}
function humanCardClass(card,playable){return `player-card${playable?playable.has(card.id)?" playable-card":" not-playable-card":""}`}
function setStatus(t,action,fn){$("#status").textContent=t;let b=$("#actionBtn");b.hidden=!action;if(action){b.textContent=action;b.onclick=fn}}
function renderMoveHistory(){let box=$("#moveHistory"),list=$("#historyList");if(!box||!list)return;box.hidden=!(moveHistory.length||document.body.classList.contains("online-active"));list.innerHTML=moveHistory.slice(-6).map(item=>`<div class="history-entry">${String(item.text||item).replace(/[&<>]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;"})[char])}</div>`).join("")}
function recordSingleHistory(text){moveHistory.push({text,at:Date.now()});moveHistory=moveHistory.slice(-8);renderMoveHistory()}
function render(){
  players[0].hand.sort((a,b)=>strength(a)-strength(b));
  let playable=humanPlayableCardIds(),seats=window.DurakRoundTable.createTableLayout(players.map(p=>p.id),0),seatById=new Map(seats.map(s=>[s.playerId,s])),opp=$("#opponents");
  opp.innerHTML=players.slice(1).map(p=>`<article data-player-id="${p.id}" style="${window.DurakRoundTable.seatStyle(seatById.get(p.id))}" class="bot-seat ${window.DurakAvatarArrival.arrivalClass(p.arrivalState)} ${p.out?"out":""} ${window.DurakAvatarArrival.seatRoleClass(turn,p.id,attacker,defender,!!battle.length)}">${window.DurakAvatarArrival.chairHTML()}${avatarHTML(p)}<div class="bot-info"><strong>${p.name}</strong><span>${p.out?"a terminat":p.hand.length+" cărți"}</span></div><div id="hand-${p.id}" class="hand bot-hand">${p.hand.map(botCardHTML).join("")}</div></article>`).join("");
  $(".you").style.cssText=window.DurakRoundTable.seatStyle(seatById.get(0));$(".you").classList.toggle("opening-arrived",!!players[0].arrived);
  $("#playerHand").innerHTML=players[0].hand.map(c=>cardHTML(c,humanCardClass(c,playable))).join("");
  $("#playerCount").textContent=`${players[0].hand.length} cărți`;$("#deckCount").textContent=deck.length;$("#deck").style.display=deck.length?"block":"none";$("#trump").innerHTML=deck.length?cardHTML(deck[0]):`<b style="font-size:35px">${trumpSuit}</b>`;$("#battlefield").innerHTML=battle.length?battle.map(p=>`<div class="pair">${cardHTML(p.attack)}${p.defense?cardHTML(p.defense,"defense"):""}</div>`).join(""):`<div class="empty-table">Masa este liberă</div>`;document.querySelectorAll(".player-card").forEach(el=>el.onclick=()=>playHuman(el.dataset.id));
}
function impact(symbol="✦"){let r=$("#battlefield").getBoundingClientRect();for(let i=0;i<8;i++){let s=document.createElement("i");s.className="spark";s.textContent=symbol;s.style.left=`${r.left+r.width/2}px`;s.style.top=`${r.top+r.height/2}px`;s.style.setProperty("--x",`${(Math.random()-.5)*240}px`);s.style.setProperty("--y",`${(Math.random()-.5)*170}px`);s.style.color=i%2?"#e9b949":"white";$("#fx").append(s);setTimeout(()=>s.remove(),900)}}
function botThrowTempo(i){let p=players[i],alive=active().length,stress=(p?.hand.length<=3?2:0)+(battle.length>=3?1:0)+(deck.length<=players.length*2?1:0)+(alive<=2?1:0);return stress>=3?560:stress>=1?790:1180}
async function animateBotThrow(i,c){document.body.classList.add("bot-landing");let duration=botThrowTempo(i),from=$(`#hand-${i}`)?.getBoundingClientRect()||$(`#avatar-${i}`)?.getBoundingClientRect(),to=$("#battlefield").getBoundingClientRect();if(!from){document.body.classList.remove("bot-landing");return}let ghost=document.createElement("div"),red=c.suit==="♥"||c.suit==="♦";ghost.className=`card bot-thrown-card ${red?"red":""} ${duration<700?"stress-throw":duration>1000?"relaxed-throw":""}`;ghost.innerHTML=`<span class="corner">${c.rank}<br>${c.suit}</span>${c.suit}<span class="corner bottom">${c.rank}<br>${c.suit}</span>`;let sx=from.left+from.width/2-39,sy=from.top+from.height/2-57,dx=to.left+to.width/2-39+(Math.random()-.5)*70-sx,dy=to.top+to.height/2-57-sy,arc=-Math.max(55,Math.min(105,Math.abs(dx)*.13));ghost.style.left=`${sx}px`;ghost.style.top=`${sy}px`;ghost.style.setProperty("--throw-duration",`${duration}ms`);let points=[["25",.25,.75],["50",.5,1],["75",.75,.75]];[["--throw-x",dx],["--throw-y",dy],...points.flatMap(([n,t,a])=>[[`--throw-x${n}`,dx*t],[`--throw-y${n}`,dy*t+arc*a]])].forEach(([k,v])=>ghost.style.setProperty(k,`${v}px`));document.body.append(ghost);botMood(i,duration<700?"angry":"happy","attack");await sleep(duration);ghost.remove();setTimeout(()=>document.body.classList.remove("bot-landing"),140)}
function renderBotLanding(){document.body.classList.add("bot-landing");render();requestAnimationFrame(()=>requestAnimationFrame(()=>document.body.classList.remove("bot-landing")))}
function createPlayers(n){let names=[...NAMES].sort(()=>Math.random()-.5),humanLook=window.DurakProfile?.publicLook?.()||{};players=[{id:0,name:window.localStorage?.getItem("durak_nickname")||"Tu",human:true,hand:[],out:false,arrived:false,arrivalState:"waiting",skin:"#d9a474",shirt:"#7e2940",hair:"#251a15",hairStyle:"classic-hair",eyeStyle:"round-eyes",facialHair:"clean-face",tattoo:"none",outfit:"coat",...humanLook}];for(let i=1;i<=n;i++)players.push({id:i,name:names[i-1],human:false,hand:[],out:false,arrived:false,arrivalState:"waiting",skin:pick(["#f1c49b","#d9a474","#bd7b52","#8b543b","#5d392d","#e2b18a"]),shirt:pick(["#7e2940","#275a76","#56713b","#6c4381","#9a572f","#26364f","#a27c2e"]),hair:pick(["#251a15","#6b492e","#c19052","#191919","#dad4c7","#8e2525"]),hairStyle:pick(["classic-hair","buzz-hair","curly-hair","mohawk-hair","long-hair","bald-hair","side-hair"]),eyeStyle:pick(["round-eyes","round-eyes","narrow-eyes","wide-eyes"]),facialHair:pick(["clean-face","clean-face","mustache","beard","goatee"]),tattoo:pick(["none","none","none","ink-left","ink-right"]),outfit:pick(["coat","sweater","vest"])});}
async function animateDealCard(playerId,card){let from=$("#deck").getBoundingClientRect(),target=playerId===0?$("#playerHand"):$(`#hand-${playerId}`),to=target.getBoundingClientRect(),ghost=document.createElement("div");ghost.className=`card opening-dealt-card ${playerId===0&&(card.suit==="♥"||card.suit==="♦")?"red":""} ${playerId!==0?"back":""}`;if(playerId===0)ghost.innerHTML=`<span class="corner">${card.rank}<br>${card.suit}</span>${card.suit}`;let sx=from.left+from.width/2-32,sy=from.top+from.height/2-48,dx=to.left+to.width/2-32-sx,dy=to.top+to.height/2-48-sy;ghost.style.left=`${sx}px`;ghost.style.top=`${sy}px`;ghost.style.setProperty("--deal-x",`${dx}px`);ghost.style.setProperty("--deal-y",`${dy}px`);ghost.style.setProperty("--deal-mid-x",`${dx*.45}px`);ghost.style.setProperty("--deal-arc",`${dy*.45-70}px`);document.body.append(ghost);await sleep(260);ghost.remove()}
async function startGame(){let run=++openingRun;createPlayers(botAmount);deck=makeDeck();battle=[];finishOrder=[];moveHistory=[];singleGameId=`single-${Date.now()}-${Math.random()}`;over=false;turn="opening";trumpSuit=deck[0].suit;$("#skipBtn").hidden=true;$("#standings").innerHTML="";$("#setup").hidden=true;$("#modal").hidden=true;$("#emoteBar").hidden=false;$("#moveHistory").hidden=false;renderMoveHistory();document.body.classList.add("opening-active");$("#playerReaction").textContent="";render();setStatus("Jucătorii vin la masă…");let timeline=window.DurakOpening.createOpeningTimeline(players),lastDealt=null;for(let event of timeline){if(run!==openingRun)return;if(event.type==="player-enter"){let p=players[event.playerId];p.arrived=true;p.arrivalState=p.human?"ready":"walking";render();setStatus(`${p.name} vine la masă…`);await sleep(p.human?180:event.duration)}else if(event.type==="chair-pull"){let p=players[event.playerId];if(!p.human){p.arrivalState="pulling-chair";render();setStatus(`${p.name} își trage scaunul de sub masă…`);await sleep(event.duration)}}else if(event.type==="player-sit"){let p=players[event.playerId];if(!p.human){p.arrivalState="sitting";render();setStatus(`${p.name} se așază la masă…`);await sleep(event.duration);p.arrivalState="ready";render()}}else if(event.type==="player-reaction"){let p=players[event.playerId],emotion=event.emotion==="happy"?"laughing":event.emotion==="angry"?"angry":"thinking",line=say(event.emotion==="happy"?"laugh":event.emotion==="angry"?"angry":"think");p.openingEmotion=emotion;p.openingLine=line;render();if(p.human){let badge=$("#playerReaction");badge.textContent=line;badge.className=`player-reaction ${emotion}`}await sleep(520);p.openingLine="";render()}else if(event.type==="deal-card"){let p=players[event.playerId],card=deck.pop();lastDealt=card;setStatus(`Se împart cărțile: ${p.name} primește cartea ${event.cardNumber}/6`);await animateDealCard(p.id,card);p.hand.push(card);render()}else if(event.type==="opening-complete"){trumpSuit=(deck.length?deck[0]:lastDealt).suit;let lowest=99;players.forEach(p=>p.hand.filter(c=>c.suit===trumpSuit).forEach(c=>{let v=RANKS.indexOf(c.rank);if(v<lowest){lowest=v;attacker=p.id}}));defender=nextActive(attacker);players.forEach(p=>{p.openingEmotion="";p.openingLine=""});$("#playerReaction").textContent="";document.body.classList.remove("opening-active");render();recordSingleHistory("Partida a început.");startRound()}}}
function markFinished(){players.forEach(p=>{if(!deck.length&&!battle.length&&!p.hand.length&&!p.out){p.out=true;finishOrder.push(p.id);if(p.human)$("#skipBtn").hidden=false}})}
function refill(){let order=[players[attacker]];for(let n=1;n<players.length;n++){let p=players[(attacker+n)%players.length];if(p.id!==defender)order.push(p)}if(players[defender]!==players[attacker])order.push(players[defender]);order.forEach(p=>{while(p.hand.length<6&&deck.length)p.hand.push(deck.pop())});markFinished()}
function showStandings(skipped=false){over=true;$("#skipBtn").hidden=true;let remaining=players.filter(p=>!finishOrder.includes(p.id)).sort((a,b)=>a.hand.length-b.hand.length),order=[...finishOrder.map(id=>players[id]),...remaining],humanPlace=order.findIndex(p=>p.human)+1;if(!skipped||finishOrder.includes(0))window.DurakProfile?.recordResult?.(singleGameId,humanPlace,order.length);$("#resultIcon").textContent="🏁";$("#resultTitle").textContent=skipped?"Clasament estimat":"Clasament final";$("#resultText").textContent=skipped?"Ai sărit restul partidei. Ordinea boților rămași este calculată după cărțile din mână.":"Partida s-a terminat.";$("#podium").innerHTML=order.slice(0,3).map((p,i)=>`<div class="podium-player place-${i+1}">${avatarHTML({...p,openingEmotion:i===0?"laughing":i===2?"angry":""})}<b>${p.name}</b><span>${i+1}</span></div>`).join("");$("#standings").innerHTML=order.map((p,i)=>`<div class="standing-row ${i===0?"winner":""} ${i===order.length-1?"durak":""}"><span class="medal">${i===0?"🥇":i===1?"🥈":i===2?"🥉":"•"}</span><b>${p.name}</b><span>${i===order.length-1?"DURAK":`LOCUL ${i+1}`}</span></div>`).join("");$("#modal").hidden=false}
function checkEnd(){markFinished();let alive=active();if(alive.length>1)return false;if(alive.length===1&&!finishOrder.includes(alive[0].id))finishOrder.push(alive[0].id);showStandings(false);return true}
async function thinkBot(i){let hand=$(`#hand-${i}`),cards=hand?[...hand.children]:[];botMood(i,"thinking deep-think","think");if(hand)hand.classList.add("choosing");for(let k=0;k<Math.min(2,cards.length+1);k++){cards.forEach(c=>c.classList.remove("considering"));let c=pick(cards);if(c)c.classList.add("considering");await sleep(READ_TIME)}if(hand)hand.classList.remove("choosing");mood(i,"","");await sleep(650)}
function startRound(){if(over||checkEnd())return;battle=[];defender=nextActive(attacker);attackLimit=Math.min(6,players[defender].hand.length);render();let a=players[attacker],d=players[defender];if(a.human){turn="humanAttack";setStatus(`Atacă-l pe ${d.name}: alege o carte.`)}else{turn="bots";setStatus(`${a.name} îl atacă pe ${d.name}…`);botRound()}}
async function botRound(){if(over)return;let a=players[attacker],d=players[defender];await thinkBot(attacker);if(over)return;let card=[...a.hand].sort((x,y)=>strength(x)-strength(y))[0];if(!card){finishRound(true);return}setStatus(`${a.name} aruncă o carte pe masă…`);await animateBotThrow(attacker,card);if(over)return;a.hand.splice(a.hand.indexOf(card),1);battle.push({attack:card});recordSingleHistory(`${a.name} a atacat cu ${card.rank}${card.suit}.`);render();impact(card.suit);if(d.human){turn="humanDefend";let taunt=maybeBotLine("attack",pick(LINES.attack));setStatus(taunt?`${a.name}: „${taunt}”`:`${a.name} te-a atacat.`,"Ia cărțile",humanTake);return}setStatus(`${d.name} se uită atent la atac…`);await sleep(1500);let defense=d.hand.filter(c=>beats(c,card)).sort((x,y)=>strength(x)-strength(y))[0];if(defense){d.hand.splice(d.hand.indexOf(defense),1);battle[0].defense=defense;recordSingleHistory(`${d.name} a apărat cu ${defense.rank}${defense.suit}.`);render();botMood(defender,"happy","laugh","Asta a fost tot?");impact("✦");let ranks=new Set(battle.flatMap(x=>[x.attack.rank,x.defense?.rank].filter(Boolean))),canJoin=players[0].hand.some(c=>ranks.has(c.rank))&&battle.length<attackLimit;if(canJoin&&!players[0].out){turn="humanAdd";setStatus(`Poți interveni în lupta dintre ${a.name} și ${d.name}: adaugă o valoare de pe masă.`,"Lasă-i să continue",()=>finishRound(true));return}setStatus(`${d.name} s-a apărat. Urmează tura următoare…`);await sleep(1800);finishRound(true)}else{botMood(defender,"worried","angry",pick(LINES.take));offerCardsBeforeTake()}}
function queueHumanAttackResponse(){clearTimeout(attackBatchTimer);attackBatchTimer=setTimeout(()=>{attackBatchTimer=null;turn="bots";botDefendHumanBatch()},ATTACK_BATCH_MS)}
function playHuman(id){if(over)return;let p=players[0],idx=p.hand.findIndex(c=>c.id===id),c=p.hand[idx];if(!c)return;if(turn==="humanAttack"||turn==="humanAttackBatch"){if(battle.length&&c.rank!==battle[0].attack.rank){setStatus("La primul atac, cărțile aruncate împreună trebuie să aibă aceeași valoare.","Trimite lotul acum",()=>{clearTimeout(attackBatchTimer);attackBatchTimer=null;turn="bots";botDefendHumanBatch()});return}if(battle.length>=attackLimit){setStatus(`Limita acestui atac este ${attackLimit} cărți — câte avea apărătorul la început.`);return}p.hand.splice(idx,1);battle.push({attack:c});recordSingleHistory(`${p.name} a atacat cu ${c.rank}${c.suit}.`);render();impact(c.suit);turn="humanAttackBatch";setStatus(`Ai aruncat ${battle.length} ${battle.length===1?"carte":"cărți"}. Mai pune rapid una de aceeași valoare sau trimite lotul.`,"Trimite lotul acum",()=>{clearTimeout(attackBatchTimer);attackBatchTimer=null;turn="bots";botDefendHumanBatch()});queueHumanAttackResponse()}else if(turn==="humanAdd"||turn==="humanAddBatch"||turn==="humanAddTaking"){let ranks=new Set(battle.flatMap(x=>[x.attack.rank,x.defense?.rank].filter(Boolean)));let taking=turn==="humanAddTaking";if(!ranks.has(c.rank)){setStatus("Regula oficială: poți adăuga doar o valoare aflată deja pe masă.",taking?"Gata, să le ia":"Trimite lotul acum",taking?finalizeBotTake:()=>{clearTimeout(attackBatchTimer);attackBatchTimer=null;turn="bots";botDefendHumanBatch()});return}if(battle.length>=attackLimit){setStatus(`Limita acestui atac este ${attackLimit} cărți — câte avea apărătorul la început.`,taking?"Gata, să le ia":"Trimite lotul acum",taking?finalizeBotTake:()=>{clearTimeout(attackBatchTimer);attackBatchTimer=null;turn="bots";botDefendHumanBatch()});return}p.hand.splice(idx,1);battle.push({attack:c});recordSingleHistory(`${p.name} a adăugat ${c.rank}${c.suit}.`);render();impact(c.suit);if(taking){turn="humanAddTaking";setStatus("Mai poți adăuga o valoare de pe masă înainte să le ia.","Gata, să le ia",finalizeBotTake)}else{turn="humanAddBatch";setStatus("Poți pune imediat încă o carte permisă sau poți trimite lotul.","Trimite lotul acum",()=>{clearTimeout(attackBatchTimer);attackBatchTimer=null;turn="bots";botDefendHumanBatch()});queueHumanAttackResponse()}}else if(turn==="humanDefend"){let open=battle.find(x=>!x.defense);if(!beats(c,open.attack)){setStatus("Cartea aceasta nu bate atacul.","Ia cărțile",humanTake);return}p.hand.splice(idx,1);open.defense=c;recordSingleHistory(`${p.name} a apărat cu ${c.rank}${c.suit}.`);render();impact("✦");turn="bots";setTimeout(()=>botsMayAddToHuman(false),1300)}}
let draggedCardId=null;
document.addEventListener("dragstart",e=>{let card=e.target.closest?.(".player-card");if(!card)return;draggedCardId=card.dataset.id;card.classList.add("dragging");e.dataTransfer.effectAllowed="move";e.dataTransfer.setData("text/plain",draggedCardId);$("#battlefield").classList.add("drop-ready")});
document.addEventListener("dragend",e=>{e.target.closest?.(".player-card")?.classList.remove("dragging");$("#battlefield").classList.remove("drop-ready","drag-over");draggedCardId=null});
$("#battlefield").addEventListener("dragover",e=>{if(!draggedCardId)return;e.preventDefault();e.dataTransfer.dropEffect="move";e.currentTarget.classList.add("drag-over")});
$("#battlefield").addEventListener("dragleave",e=>{if(!e.currentTarget.contains(e.relatedTarget))e.currentTarget.classList.remove("drag-over")});
$("#battlefield").addEventListener("drop",e=>{e.preventDefault();let id=e.dataTransfer.getData("text/plain")||draggedCardId;e.currentTarget.classList.remove("drop-ready","drag-over");draggedCardId=null;if(id)playHuman(id)});
async function botDefendHuman(){let d=players[defender];setStatus(`${d.name} caută o apărare…`);await thinkBot(defender);let open=battle.find(x=>!x.defense),card=d.hand.filter(c=>beats(c,open.attack)).sort((a,b)=>strength(a)-strength(b))[0];if(card){d.hand.splice(d.hand.indexOf(card),1);open.defense=card;render();impact("✦");botMood(defender,"happy","laugh","Te-am prins!");turn="humanAdd";setStatus(`${d.name} s-a apărat. Poți adăuga orice valoare aflată pe masă.`,"Gata, încheie tura",()=>finishRound(true))}else{botMood(defender,"worried","angry",pick(LINES.take));offerCardsBeforeTake()}}
async function botDefendHumanBatch(){if(over)return;let d=players[defender],openCards=battle.filter(x=>!x.defense);if(!openCards.length)return;setStatus(`${d.name} caută apărare pentru ${openCards.length} ${openCards.length===1?"carte":"cărți"}…`);await thinkBot(defender);for(let open of openCards){let card=d.hand.filter(c=>beats(c,open.attack)).sort((a,b)=>strength(a)-strength(b))[0];if(!card){render();botMood(defender,"worried","angry",pick(LINES.take));offerCardsBeforeTake();return}d.hand.splice(d.hand.indexOf(card),1);open.defense=card;render();impact("✦");await sleep(420)}botMood(defender,"happy","laugh","Le-am prins pe toate!");turn="humanAdd";setStatus(`${d.name} a apărat lotul. Poți adăuga rapid alte valori aflate pe masă.`,"Gata, încheie tura",()=>finishRound(true))}
async function botDefendAdded(){let d=players[defender];setStatus(`${d.name} încearcă să apere și noua carte…`);await thinkBot(defender);let open=battle.find(x=>!x.defense),card=d.hand.filter(c=>beats(c,open.attack)).sort((a,b)=>strength(a)-strength(b))[0];if(card){d.hand.splice(d.hand.indexOf(card),1);open.defense=card;render();impact("✦");turn="humanAdd";setStatus("S-a apărat din nou. Mai poți adăuga sau poți încheia.","Gata, încheie tura",()=>finishRound(true))}else{botMood(defender,"worried","angry",pick(LINES.take));offerCardsBeforeTake()}}
function offerCardsBeforeTake(){let d=players[defender],ranks=new Set(battle.flatMap(x=>[x.attack.rank,x.defense?.rank].filter(Boolean))),canAdd=players[0].hand.some(c=>ranks.has(c.rank))&&battle.length<attackLimit;if(canAdd&&!players[0].out){turn="humanAddTaking";setStatus(`${d.name} a spus că ia. Mai poți adăuga o carte permisă înainte să le ridice.`,"Gata, să le ia",finalizeBotTake)}else finalizeBotTake()}
async function finalizeBotTake(){let d=players[defender];turn="bots";setStatus(`${d.name} ia toate cărțile de pe masă…`);await sleep(2500);d.hand.push(...battle.flatMap(x=>[x.attack,x.defense].filter(Boolean)));battle=[];finishRound(false)}
function humanTake(){if(turn!=="humanDefend")return;turn="bots";recordSingleHistory(`${players[0].name} ia cărțile.`);setStatus("Ai spus că iei. Ceilalți boți mai pot adăuga…");botsMayAddToHuman(true)}
async function botsMayAddToHuman(taking){if(over)return;let ranks=new Set(battle.flatMap(x=>[x.attack.rank,x.defense?.rank].filter(Boolean)));let order=[];for(let n=0;n<players.length;n++){let p=players[(attacker+n)%players.length];if(!p.human&&!p.out)order.push(p)}let thrower=order.find(p=>p.hand.some(c=>ranks.has(c.rank)));if(!thrower||battle.length>=attackLimit){if(taking)finalizeHumanTake();else finishRound(true);return}let card=thrower.hand.filter(c=>ranks.has(c.rank)).sort((a,b)=>strength(a)-strength(b))[0];setStatus(`${thrower.name} mai caută o carte pentru atac…`);await thinkBot(thrower.id);if(over)return;setStatus(`${thrower.name} aruncă și el o carte…`);await animateBotThrow(thrower.id,card);if(over)return;thrower.hand.splice(thrower.hand.indexOf(card),1);battle.push({attack:card});render();impact(card.suit);botMood(thrower.id,"happy","attack",pick(LINES.attack));if(taking){setStatus(`${thrower.name} îți mai adaugă o carte înainte să le iei.`);await sleep(2500);botsMayAddToHuman(true)}else{turn="humanDefend";setStatus(`${thrower.name} a intrat în atac. Apără noua carte.`,"Ia cărțile",humanTake)}}
async function finalizeHumanTake(){turn="bots";setStatus("Iei toate cărțile de pe masă…");await sleep(2500);players[0].hand.push(...battle.flatMap(x=>[x.attack,x.defense].filter(Boolean)));battle=[];finishRound(false)}
function finishRound(defended){if(over)return;let oldDef=defender;battle=[];refill();if(checkEnd()){render();return}attacker=defended&&!players[oldDef].out?oldDef:nextActive(oldDef);render();setTimeout(startRound,650)}
for(const kind of Object.keys(LINES)){let sourceKind=kind==="take"?"angry":kind==="win"?"laugh":kind;LINES[kind]=Array.from({length:32},()=>say(sourceKind))}
const unsanitizedMood=mood;
mood=(i,type,text="")=>{let kind=type.includes("happy")||type.includes("laugh")?"laugh":type.includes("worried")||type.includes("angry")||type.includes("sad")||type.includes("panic")?"angry":"think";return unsanitizedMood(i,type,text?window.DurakMoldovanVocabulary.sanitizePhrase(text,kind):"")};
document.querySelectorAll("[data-emote]").forEach(button=>button.addEventListener("click",()=>{if(document.body.classList.contains("online-active")||over||turn==="idle")return;let kind=button.dataset.emote,line=say(kind),badge=$("#playerReaction");badge.textContent=line;badge.className=`player-reaction ${kind==="angry"?"angry":kind==="think"?"thinking":"laughing"}`;clearTimeout(humanReactionTimer);humanReactionTimer=setTimeout(()=>{if(badge.textContent===line){badge.textContent="";badge.className="player-reaction"}},3000)}));
$("#lessBots").onclick=()=>{$("#botNumber").textContent=botAmount=Math.max(1,botAmount-1)};$("#moreBots").onclick=()=>{$("#botNumber").textContent=botAmount=Math.min(5,botAmount+1)};$("#startGame").onclick=startGame;$("#newGame").onclick=()=>{openingRun++;document.body.classList.remove("opening-active");over=true;turn="idle";$("#skipBtn").hidden=true;$("#emoteBar").hidden=true;$("#moveHistory").hidden=true;$("#setup").hidden=false};$("#playAgain").onclick=()=>{$("#modal").hidden=true;$("#emoteBar").hidden=true;$("#moveHistory").hidden=true;$("#setup").hidden=false};$("#skipBtn").onclick=()=>showStandings(true);
