(()=>{
const ui=id=>document.getElementById(id);let peer=null,isHost=false,room="",myPlayerId=null,nextPlayerNumber=0,connections=[],onlineState=null,onlineActive=false,publicHosting=false,reactionTimer=null,reactionViewTimer=null,onlineAttackBatchTimer=null,onlineTurnTimer=null,turnClockTimer=null,joinTimer=null,antiSpamTimer=null,reconnectTimer=null,migrationTimer=null,reconnectDeadline=0,localEmoteAt=0,joinRejected=false,intentionalShutdown=false,migrationInProgress=false,onlineOpeningVisual=null,onlineOpeningRun=0,pendingOnlineState=null,hostBackup=null,sessionToken="",localActionTimes=[],playerSessions=new Map(),disconnectTimers=new Map();
const JOIN_TIMEOUT_MS=Number(window.__DURAK_JOIN_TIMEOUT_MS)||12000;
const ONLINE_OPENING_SPEED=Math.max(0,Number(window.__DURAK_OPENING_SPEED??1));
const TURN_TIMEOUT_MS=Number(window.__DURAK_TURN_TIMEOUT_MS)||30000;
const RECONNECT_WINDOW_MS=Number(window.__DURAK_RECONNECT_WINDOW_MS)||60000;
const ACTION_RATE_WINDOW_MS=2000,ACTION_RATE_MAX=10,ACTION_BLOCK_MS=3000;
const ranks=["6","7","8","9","10","J","Q","K","A"],suits=["♠","♥","♦","♣"];
const rank=c=>ranks.indexOf(c.rank)+(c.suit===onlineState?.trump?20:0),beatsOnline=(d,a)=>(d.suit===a.suit&&rank(d)>rank(a))||(d.suit===onlineState.trump&&a.suit!==onlineState.trump);
const status=(t,bad=false)=>{ui("networkStatus").textContent=t;ui("networkStatus").className=`network-status ${bad?"error":"ok"}`};
const cleanOnlineName=value=>(String(value||"").trim().replace(/\s+/g," ").slice(0,16)||"Jucător"),onlineNameKey=value=>cleanOnlineName(value).normalize("NFKC").toLocaleLowerCase("ro"),escapeOnlineHtml=value=>String(value).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char]);
const cleanRoomCode=value=>String(value||"").toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,6);
const cleanSessionToken=value=>String(value||"").replace(/[^a-zA-Z0-9_-]/g,"").slice(0,80);
function roomSessionToken(){let key=`durak_session_${room}`,saved="";try{saved=window.sessionStorage?.getItem(key)||""}catch{}if(saved)return cleanSessionToken(saved);let bytes=window.crypto?.getRandomValues?window.crypto.getRandomValues(new Uint32Array(4)):null,token=bytes?Array.from(bytes,value=>value.toString(36)).join(""):`${Date.now().toString(36)}${Math.random().toString(36).slice(2)}`;try{window.sessionStorage?.setItem(key,token)}catch{}return token}
function notifyOnlineLeave(){if(!isHost&&myPlayerId&&connections[0]?.open)send(connections[0],{type:"leave"})}
function cleanPeer(){intentionalShutdown=true;notifyOnlineLeave();onlineOpeningRun++;onlineOpeningVisual=null;pendingOnlineState=null;hostBackup=null;localActionTimes=[];[reactionTimer,reactionViewTimer,onlineAttackBatchTimer,onlineTurnTimer,turnClockTimer,joinTimer,antiSpamTimer,reconnectTimer,migrationTimer].forEach(clearTimeout);disconnectTimers.forEach(clearTimeout);disconnectTimers.clear();joinTimer=null;onlineTurnTimer=null;turnClockTimer=null;reconnectTimer=null;migrationTimer=null;document.body.classList.remove("online-active","opening-active");ui("playerReaction").textContent="";ui("turnTimer").hidden=true;ui("emoteBar").hidden=true;ui("moveHistory").hidden=true;if(publicHosting&&room)window.DurakAuth?.closeRoom(room);publicHosting=false;if(peer)peer.destroy();peer=null;connections=[];onlineActive=false;joinRejected=false;migrationInProgress=false;playerSessions.clear();intentionalShutdown=false}
function reactOnline(playerId,kind){let reaction=window.DurakMultiplayerReactions.createMultiplayerReaction(playerId,kind);if(!reaction)return;onlineState.reaction=reaction;clearTimeout(reactionTimer);reactionTimer=setTimeout(()=>{if(isHost&&onlineState?.reaction?.id===reaction.id){delete onlineState.reaction;sync()}},Math.max(0,reaction.expiresAt-Date.now()))}
const waitOnline=ms=>new Promise(resolve=>setTimeout(resolve,ms*ONLINE_OPENING_SPEED));
function createOnlineOpening(players){let emotions=["happy","angry","neutral"];return{id:`${Date.now()}-${Math.random().toString(36).slice(2,7)}`,reactions:players.map(player=>{let emotion=emotions[Math.floor(Math.random()*emotions.length)],kind=emotion==="happy"?"laugh":emotion==="angry"?"angry":"think";return{playerId:player.id,emotion,phrase:window.DurakMoldovanVocabulary.say(kind)}})}}
function openingReactionPlayer(player,reaction){if(!reaction)return player;return{...player,openingEmotion:reaction.emotion==="happy"?"laughing":reaction.emotion,openingLine:reaction.phrase,forceDialogue:true}}
function renderOnlineOpeningFrame(s){
  let visual=onlineOpeningVisual,me=s.players.find(player=>player.id===myPlayerId);if(!visual||!me?.hand)return;
  ui("turnTimer").hidden=true;
  let visiblePlayers=s.players.filter(player=>!player.left),others=visiblePlayers.filter(player=>player.id!==me.id),seats=window.DurakRoundTable.createTableLayout(visiblePlayers.map(player=>player.id),me.id),seatById=new Map(seats.map(seat=>[seat.playerId,seat])),selfReaction=visual.activeReaction?.playerId===me.id?visual.activeReaction:null,badge=ui("playerReaction");
  badge.textContent=selfReaction?.phrase||"";badge.className=`player-reaction ${selfReaction?.emotion||""}`;
  ui("opponents").innerHTML=others.map(player=>{let count=visual.dealt[player.id]||0,reaction=visual.activeReaction?.playerId===player.id?visual.activeReaction:null,state=visual.arrivals[player.id]||"waiting";return `<article data-player-id="${player.id}" style="${window.DurakRoundTable.seatStyle(seatById.get(player.id))}" class="bot-seat ${window.DurakAvatarArrival.arrivalClass(state)}">${window.DurakAvatarArrival.chairHTML()}${avatarHTML(openingReactionPlayer(player,reaction))}<div class="bot-info"><strong>${escapeOnlineHtml(player.name)}</strong><span>${count} cărți</span></div><div id="hand-${player.id}" class="hand bot-hand">${Array.from({length:count},()=>botCardHTML()).join("")}</div></article>`}).join("");
  let you=document.querySelector(".you");you.style.cssText=window.DurakRoundTable.seatStyle(seatById.get(me.id));you.classList.toggle("opening-arrived",(visual.arrivals[me.id]||"waiting")!=="waiting");you.classList.remove("active-turn");
  let ownCount=visual.dealt[me.id]||0;ui("playerHand").innerHTML=me.hand.slice(0,ownCount).map(card=>cardHTML(card,"player-card")).join("");ui("playerCount").textContent=`${ownCount} cărți`;
  let finalDeckCount=s.deckCount??s.deck?.length??0,remaining=finalDeckCount+(s.players.length*6)-visual.dealtTotal;ui("deckCount").textContent=remaining;ui("deck").style.display=remaining?"block":"none";let trumpCard=s.trumpCard??s.deck?.[0];ui("trump").innerHTML=trumpCard?cardHTML(trumpCard):`<b style="font-size:35px">${s.trump}</b>`;ui("battlefield").innerHTML='<div class="empty-table">Masa este liberă</div>';setStatus(visual.status||"Jucătorii vin la masă…");
}
async function animateOnlineDealCard(playerId,card){let from=ui("deck")?.getBoundingClientRect?.(),target=playerId===myPlayerId?ui("playerHand"):document.querySelector(`[data-player-id="${playerId}"] .bot-hand`),to=target?.getBoundingClientRect?.();if(!from||!to){await waitOnline(260);return}let ghost=document.createElement("div"),mine=playerId===myPlayerId,red=mine&&(card?.suit==="♥"||card?.suit==="♦");ghost.className=`card opening-dealt-card ${mine?red?"red":"":"back"}`;if(mine&&card)ghost.innerHTML=`<span class="corner">${card.rank}<br>${card.suit}</span>${card.suit}`;let sx=from.left+from.width/2-32,sy=from.top+from.height/2-48,dx=to.left+to.width/2-32-sx,dy=to.top+to.height/2-48-sy;ghost.style.left=`${sx}px`;ghost.style.top=`${sy}px`;ghost.style.setProperty("--deal-x",`${dx}px`);ghost.style.setProperty("--deal-y",`${dy}px`);ghost.style.setProperty("--deal-mid-x",`${dx*.45}px`);ghost.style.setProperty("--deal-arc",`${dy*.45-70}px`);document.body.append(ghost);await waitOnline(260);ghost.remove()}
async function runOnlineOpening(s){
  let id=s.opening.id,run=++onlineOpeningRun,reactions=new Map(s.opening.reactions.map(reaction=>[reaction.playerId,reaction]));onlineOpeningVisual={id,running:true,completed:false,arrivals:Object.fromEntries(s.players.map(player=>[player.id,"waiting"])),dealt:Object.fromEntries(s.players.map(player=>[player.id,0])),dealtTotal:0,activeReaction:null,status:"Jucătorii vin la masă…"};document.body.classList.add("opening-active");renderOnlineOpeningFrame(s);
  let timeline=window.DurakOpening.createOpeningTimeline(s.players,{reactionFor:player=>reactions.get(player.id)?.emotion||"neutral"});
  for(let event of timeline){if(run!==onlineOpeningRun)return;let player=s.players.find(item=>item.id===event.playerId),mine=event.playerId===myPlayerId;if(event.type==="opening-start")continue;if(event.type==="player-enter"){onlineOpeningVisual.arrivals[event.playerId]=mine?"ready":"walking";onlineOpeningVisual.status=`${player.name} vine la masă…`;renderOnlineOpeningFrame(s);await waitOnline(mine?180:event.duration)}else if(event.type==="chair-pull"){if(!mine){onlineOpeningVisual.arrivals[event.playerId]="pulling-chair";onlineOpeningVisual.status=`${player.name} își trage scaunul…`;renderOnlineOpeningFrame(s);await waitOnline(event.duration)}}else if(event.type==="player-sit"){if(!mine){onlineOpeningVisual.arrivals[event.playerId]="sitting";onlineOpeningVisual.status=`${player.name} se așază la masă…`;renderOnlineOpeningFrame(s);await waitOnline(event.duration);onlineOpeningVisual.arrivals[event.playerId]="ready";renderOnlineOpeningFrame(s)}}else if(event.type==="player-reaction"){onlineOpeningVisual.activeReaction=reactions.get(event.playerId)||null;renderOnlineOpeningFrame(s);await waitOnline(520);onlineOpeningVisual.activeReaction=null;renderOnlineOpeningFrame(s)}else if(event.type==="deal-card"){onlineOpeningVisual.status=`Se împart cărțile: ${player.name} primește ${event.cardNumber}/6`;renderOnlineOpeningFrame(s);let card=mine?player.hand[event.cardNumber-1]:null;await animateOnlineDealCard(event.playerId,card);onlineOpeningVisual.dealt[event.playerId]++;onlineOpeningVisual.dealtTotal++;renderOnlineOpeningFrame(s)}}
  if(run!==onlineOpeningRun)return;onlineOpeningVisual.running=false;onlineOpeningVisual.completed=true;document.body.classList.remove("opening-active");if(isHost&&onlineState?.opening?.id===id){delete onlineState.opening;scheduleOnlineTurnTimeout();sync()}else if(pendingOnlineState){onlineState=pendingOnlineState;pendingOnlineState=null;renderOnline()}else{onlineOpeningVisual.status="Ceremonia s-a terminat. Așteaptă gazda…";renderOnlineOpeningFrame(s)}
}
function openLobby(){ui("mainMenu").hidden=true;ui("setup").hidden=true;ui("onlineLobby").hidden=false;ui("lobbyChoices").hidden=false;ui("joinArea").hidden=true;ui("publicArea").hidden=true;ui("roomArea").hidden=true;status("")}
ui("singleMode").onclick=()=>{cleanPeer();ui("mainMenu").hidden=true;ui("setup").hidden=false};ui("multiMode").onclick=openLobby;
ui("singleBack").onclick=()=>{ui("setup").hidden=true;ui("mainMenu").hidden=false};
ui("lobbyBack").onclick=()=>{cleanPeer();ui("onlineLobby").hidden=true;ui("mainMenu").hidden=false};ui("showJoin").onclick=()=>{ui("lobbyChoices").hidden=true;ui("joinArea").hidden=false};
function code(){return Math.random().toString(36).slice(2,8).toUpperCase()}
function ensurePeer(id){if(typeof Peer==="undefined"){status("PeerJS nu s-a încărcat. Verifică internetul.",true);return null}return new Peer(id,{debug:1,config:{iceServers:[{urls:"stun:stun.l.google.com:19302"},{urls:"stun:stun1.l.google.com:19302"},{urls:"stun:stun.cloudflare.com:3478"}]}})}
function connectGuestToHost(reconnecting=false){if(!peer||intentionalShutdown||isHost)return;let c=peer.connect(`durak-${room.toLowerCase()}`,{reliable:true}),opened=false;connections=[c];clearTimeout(joinTimer);joinTimer=setTimeout(()=>{joinTimer=null;if(opened||joinRejected)return;if(reconnecting){scheduleGuestReconnect()}else{joinRejected=true;status("Nu s-a putut face legătura. Rețeaua poate bloca WebRTC; oprește VPN-ul sau încearcă altă rețea.",true)}},reconnecting?4000:JOIN_TIMEOUT_MS);c.on("open",()=>{opened=true;clearTimeout(joinTimer);joinTimer=null;c.send({type:"join",name:cleanOnlineName(ui("onlineName").value),token:sessionToken,reconnect:reconnecting,look:window.DurakProfile?.publicLook?.()});status(reconnecting?"Reconectare reușită. Se sincronizează partida…":"Conectat. Așteaptă gazda.")});c.on("data",receive);c.on("close",()=>{clearTimeout(joinTimer);joinTimer=null;if(intentionalShutdown||isHost)return;if(onlineActive)beginGuestRecovery();else if(reconnecting)scheduleGuestReconnect();else if(!joinRejected)status("Gazda a închis camera.",true)});c.on("error",()=>{clearTimeout(joinTimer);joinTimer=null;if(onlineActive||reconnecting)scheduleGuestReconnect();else{joinRejected=true;status("Conexiunea a eșuat. Încearcă fără VPN sau de pe altă rețea.",true)}})}
function scheduleGuestReconnect(){if(intentionalShutdown||isHost)return;clearTimeout(reconnectTimer);if(!reconnectDeadline)reconnectDeadline=Date.now()+RECONNECT_WINDOW_MS;if(Date.now()>=reconnectDeadline){status("Reconectarea nu a reușit în 60 de secunde.",true);return}status(`Reconectare automată… ${Math.max(1,Math.ceil((reconnectDeadline-Date.now())/1000))}s`);reconnectTimer=setTimeout(()=>connectGuestToHost(true),1200)}
function beginGuestRecovery(){if(intentionalShutdown||migrationInProgress)return;if(onlineState?.hostSuccessor===myPlayerId&&hostBackup)return becomeMigratedHost();scheduleGuestReconnect()}
ui("hostRoom").onclick=()=>{intentionalShutdown=false;isHost=true;room=code();sessionToken=roomSessionToken();peer=ensurePeer(`durak-${room.toLowerCase()}`);if(!peer)return;ui("lobbyChoices").hidden=true;ui("publicArea").hidden=true;ui("roomArea").hidden=false;ui("copyCode").textContent=room;peer.on("open",async()=>{connections=[];playerSessions.clear();nextPlayerNumber=1;myPlayerId="player-0";playerSessions.set(sessionToken,myPlayerId);onlineState={lobby:[{id:myPlayerId,name:cleanOnlineName(ui("onlineName").value||"Gazdă"),host:true,ready:false,look:window.DurakProfile?.publicLook?.()}]};drawLobby();status("Camera este gata. Trimite codul unui prieten.");if(publicHosting){try{await window.DurakAuth.createRoom(room,`Masa lui ${onlineState.lobby[0].name}`);status("Masa publică este vizibilă. Așteaptă jucători.")}catch(e){publicHosting=false;status(e.message,true)}}});peer.on("connection",acceptConnection);peer.on("error",e=>status(`Eroare: ${e.type}`,true))};
ui("joinRoom").onclick=()=>{intentionalShutdown=false;isHost=false;joinRejected=false;reconnectDeadline=0;room=cleanRoomCode(ui("roomCode").value);ui("roomCode").value=room;if(!room)return status("Introdu codul camerei.",true);sessionToken=roomSessionToken();peer=ensurePeer();if(!peer)return;ui("joinArea").hidden=true;ui("roomArea").hidden=false;ui("copyCode").textContent=room;status("Se caută camera…");peer.on("open",()=>connectGuestToHost(false));peer.on("error",e=>{clearTimeout(joinTimer);joinTimer=null;if(onlineActive){scheduleGuestReconnect();return}joinRejected=true;status(e.type==="peer-unavailable"?"Camera nu există sau gazda a închis pagina.":e.type==="network"||e.type==="socket-error"||e.type==="socket-closed"?"Serviciul multiplayer este blocat de rețea. Încearcă fără VPN sau de pe altă rețea.":`Eroare de conectare: ${e.type}`,true)})};
function allowConnectionAction(connection,now=Date.now()){if(now<(connection.actionBlockedUntil||0))return false;connection.actionTimes=(connection.actionTimes||[]).filter(time=>now-time<ACTION_RATE_WINDOW_MS);if(connection.actionTimes.length>=ACTION_RATE_MAX){connection.actionBlockedUntil=now+ACTION_BLOCK_MS;connection.actionTimes=[];send(connection,{type:"rateLimit",message:"Anti-spam: prea multe comenzi. Pauză 3 secunde."});return false}connection.actionTimes.push(now);return true}
function showAntiSpam(message="Anti-spam: prea multe comenzi. Pauză 3 secunde."){let badge=ui("playerReaction");badge.textContent=message;badge.className="player-reaction angry";clearTimeout(antiSpamTimer);antiSpamTimer=setTimeout(()=>{if(badge.textContent===message){badge.textContent="";badge.className="player-reaction"}},ACTION_BLOCK_MS)}
function acceptConnection(c){
  if(!onlineActive&&connections.length>=5){c.on("open",()=>c.send({type:"error",message:"Camera este plină."}));return}
  connections.push(c);
  c.on("data",d=>{
    if(d.type==="join"&&!c.playerId){let name=cleanOnlineName(d.name),token=cleanSessionToken(d.token);if(onlineActive){let reconnectId=playerSessions.get(token),player=onlineState.players.find(item=>item.id===reconnectId);if(!token||!player||player.left){send(c,{type:"error",message:"Partida a început deja și această sesiune nu poate fi recuperată."});setTimeout(()=>c.close(),120);return}let old=connections.find(item=>item!==c&&item.playerId===reconnectId);if(old){old.replaced=true;old.close()}c.playerId=reconnectId;player.disconnected=false;clearTimeout(disconnectTimers.get(reconnectId));disconnectTimers.delete(reconnectId);send(c,{type:"welcome",playerId:reconnectId,reconnected:true});recordOnlineHistory(`${player.name} s-a reconectat.`);sync();return}if(onlineState.lobby.some(player=>onlineNameKey(player.name)===onlineNameKey(name))){send(c,{type:"error",message:"Acest nickname este deja folosit în lobby. Alege altul."});connections=connections.filter(connection=>connection!==c);setTimeout(()=>c.close(),120);return}c.playerId=`player-${nextPlayerNumber++}`;if(token)playerSessions.set(token,c.playerId);onlineState.lobby.push({id:c.playerId,name,ready:false,look:window.DurakProfile?.sanitizeLook?.(d.look)||d.look});send(c,{type:"welcome",playerId:c.playerId});broadcastLobby()}
    else if(d.type==="ready"&&c.playerId&&!onlineActive){let player=onlineState.lobby.find(item=>item.id===c.playerId);if(player){player.ready=!!d.ready;broadcastLobby()}}
    else if(d.type==="action"&&c.playerId){if(allowConnectionAction(c))processAction(c.playerId,d.action)}
    else if(d.type==="emote"&&c.playerId){let now=Date.now();if(now-(c.lastEmoteAt||0)>=4000){c.lastEmoteAt=now;reactOnline(c.playerId,d.kind);sync()}else send(c,{type:"rateLimit",message:"Reacțiile au pauză 4 secunde."})}
    else if(d.type==="leave"&&c.playerId){c.intentionalLeave=true;connections=connections.filter(x=>x!==c);if(onlineActive)removeOnlinePlayer(c.playerId);else{onlineState.lobby=onlineState.lobby.filter(player=>player.id!==c.playerId);broadcastLobby()}setTimeout(()=>c.close(),0)}
  });
  c.on("close",()=>{connections=connections.filter(x=>x!==c);if(c.replaced||c.intentionalLeave)return;if(!onlineActive){onlineState.lobby=onlineState.lobby.filter(player=>player.id!==c.playerId);broadcastLobby()}else if(c.playerId)markOnlineDisconnected(c.playerId)})
}
function send(c,d){if(c?.open)c.send(d)}function broadcast(d){connections.forEach(c=>send(c,d))}function broadcastLobby(){drawLobby();broadcast({type:"lobby",lobby:onlineState.lobby})}
function receive(d){if(d.type==="welcome"){clearTimeout(joinTimer);clearTimeout(reconnectTimer);joinTimer=null;reconnectTimer=null;reconnectDeadline=0;joinRejected=false;myPlayerId=d.playerId}if(d.type==="lobby"){clearTimeout(joinTimer);joinTimer=null;onlineState={lobby:d.lobby};drawLobby()}if(d.type==="state"){clearTimeout(joinTimer);clearTimeout(reconnectTimer);joinTimer=null;reconnectTimer=null;reconnectDeadline=0;myPlayerId=d.playerId||myPlayerId;let incoming=window.DurakMultiplayerSession.localizeReactionForClient(d.state);if(onlineOpeningVisual?.running&&!incoming.opening){pendingOnlineState=incoming;return}onlineState=incoming;onlineActive=true;document.body.classList.add("online-active");ui("onlineLobby").hidden=true;ui("emoteBar").hidden=false;ui("moveHistory").hidden=false;status(onlineState.players.find(player=>player.id===myPlayerId)?.disconnected?"Se recuperează conexiunea…":"Conectat la partidă.");renderOnline()}if(d.type==="hostBackup"){hostBackup=d.backup}if(d.type==="rateLimit")showAntiSpam(d.message);if(d.type==="error"||d.type==="kicked"){clearTimeout(joinTimer);joinTimer=null;joinRejected=true;status(d.message,true)}}
function kickLobbyPlayer(playerId){if(!isHost||onlineActive||playerId===myPlayerId)return;let connection=connections.find(item=>item.playerId===playerId),player=onlineState?.lobby.find(item=>item.id===playerId);if(!connection||!player)return;send(connection,{type:"kicked",message:"Gazda te-a scos din lobby."});onlineState.lobby=onlineState.lobby.filter(item=>item.id!==playerId);connections=connections.filter(item=>item!==connection);broadcastLobby();setTimeout(()=>connection.close(),120)}
function drawLobby(){let list=onlineState?.lobby||[],readyCount=list.filter(player=>player.ready).length,view=window.DurakMultiplayerSession.lobbyStatusFor(list.length,isHost,readyCount),box=ui("onlinePlayers"),me=list.find(player=>player.id===myPlayerId);box.innerHTML=list.map((p,i)=>`<div class="online-player ${p.ready?"is-ready":""}"><b>${escapeOnlineHtml(p.name)}</b><span>${i===0?"Gazdă · ":""}${p.ready?"✓ Pregătit":"Așteaptă"}</span>${isHost&&!p.host?`<button class="lobby-kick" data-kick="${p.id}" aria-label="Dă afară ${escapeOnlineHtml(p.name)}">Dă afară</button>`:""}</div>`).join("");box.querySelectorAll("button[data-kick]").forEach(button=>button.onclick=()=>kickLobbyPlayer(button.dataset.kick));ui("readyOnline").textContent=me?.ready?"Nu mai sunt gata":"Sunt gata";ui("readyOnline").classList.toggle("is-ready",!!me?.ready);ui("startOnline").hidden=!view.canStart;status(view.message)}
ui("readyOnline").onclick=()=>{let me=onlineState?.lobby?.find(player=>player.id===myPlayerId);if(!me)return;let ready=!me.ready;if(isHost){me.ready=ready;broadcastLobby()}else{me.ready=ready;drawLobby();send(connections[0],{type:"ready",ready})}};
ui("copyCode").onclick=async()=>{try{await navigator.clipboard.writeText(room);status("Cod copiat!")}catch{status(`Cod: ${room}`)}};
async function showPublicRooms(){if(!await window.DurakAuth?.requireAccount())return;ui("lobbyChoices").hidden=true;ui("joinArea").hidden=true;ui("publicArea").hidden=false;let box=ui("publicRooms");box.innerHTML="Se caută mese…";try{let rooms=await window.DurakAuth.listRooms();box.innerHTML=rooms.length?rooms.map(r=>`<div class="public-room"><div><b>${r.name}</b><br><span>${r.players}/${r.max_players} jucători</span></div><code>${r.code}</code><button data-room="${r.id}">Intră</button></div>`).join(""):`<p>Nu există mese. Creează tu prima masă!</p>`;box.querySelectorAll("button[data-room]").forEach(b=>b.onclick=async()=>{try{let c=await window.DurakAuth.joinRoom(b.dataset.room);ui("roomCode").value=c;ui("joinRoom").click()}catch(e){ui("publicStatus").textContent=e.message}})}catch(e){box.innerHTML="";ui("publicStatus").textContent=e.message}}
if(ui("publicRoomsBtn"))ui("publicRoomsBtn").onclick=showPublicRooms;if(ui("refreshRooms"))ui("refreshRooms").onclick=showPublicRooms;if(ui("createPublicBtn"))ui("createPublicBtn").onclick=async()=>{if(!await window.DurakAuth?.requireAccount())return;publicHosting=true;ui("hostRoom").click()};
ui("startOnline").onclick=()=>{if(!isHost||onlineState.lobby.length<2||(!window.__DURAK_SKIP_READY_CHECK&&onlineState.lobby.some(player=>!player.ready)))return;if(publicHosting)window.DurakAuth?.closeRoom(room,"playing");onlineState=window.DurakMultiplayerSession.startGame(onlineState.lobby);onlineState.hostPlayerId=myPlayerId;if(!window.__DURAK_SKIP_ONLINE_OPENING)onlineState.opening=createOnlineOpening(onlineState.players);onlineActive=true;document.body.classList.add("online-active");ui("onlineLobby").hidden=true;ui("emoteBar").hidden=false;ui("moveHistory").hidden=false;recordOnlineHistory("Partida multiplayer a început.");scheduleOnlineTurnTimeout();sync()};
function recordOnlineHistory(text){if(!onlineState?.players||!text)return;onlineState.history=[...(onlineState.history||[]),{id:`${Date.now()}-${Math.random()}`,text,at:Date.now()}].slice(-8)}
function onlineSuccessor(){return onlineState?.players?.filter(player=>player.id!==myPlayerId&&!player.left&&!player.out&&!player.disconnected).sort((a,b)=>a.id.localeCompare(b.id))[0]?.id||null}
function sync(){if(isHost&&onlineState?.players){onlineState.hostPlayerId=myPlayerId;onlineState.hostSuccessor=onlineSuccessor()}renderOnline();connections.forEach(c=>send(c,{type:"state",playerId:c.playerId,state:window.DurakMultiplayerSession.viewForPlayer(onlineState,c.playerId)}));if(isHost&&onlineState?.players&&onlineState.hostSuccessor){let successor=connections.find(c=>c.playerId===onlineState.hostSuccessor);send(successor,{type:"hostBackup",backup:{state:JSON.parse(JSON.stringify(onlineState)),sessions:[...playerSessions],nextPlayerNumber}})}}
function markOnlineDisconnected(playerId){let p=playerById(playerId);if(!p||p.left||p.disconnected)return;p.disconnected=true;recordOnlineHistory(`${p.name} și-a pierdut conexiunea. Are 60 de secunde să revină.`);clearTimeout(disconnectTimers.get(playerId));disconnectTimers.set(playerId,setTimeout(()=>{disconnectTimers.delete(playerId);if(playerById(playerId)?.disconnected)removeOnlinePlayer(playerId)},RECONNECT_WINDOW_MS));sync()}
function becomeMigratedHost(){if(migrationInProgress||!hostBackup?.state)return;migrationInProgress=true;clearTimeout(reconnectTimer);reconnectTimer=null;let backup=hostBackup,oldHost=backup.state.hostPlayerId;onlineState=backup.state;nextPlayerNumber=backup.nextPlayerNumber||onlineState.players.length;playerSessions=new Map(backup.sessions||[]);hostBackup=null;isHost=true;intentionalShutdown=true;try{peer?.destroy()}catch{}intentionalShutdown=false;connections=[];if(oldHost&&oldHost!==myPlayerId){recordOnlineHistory(`${playerById(oldHost)?.name||"Gazda"} a ieșit. ${playerById(myPlayerId)?.name||"Alt jucător"} este noua gazdă.`);removeOnlinePlayer(oldHost)}let claim=()=>{peer=ensurePeer(`durak-${room.toLowerCase()}`);if(!peer)return;peer.on("open",()=>{migrationInProgress=false;onlineActive=true;status("Ești noua gazdă. Partida continuă.");scheduleOnlineTurnTimeout();sync()});peer.on("connection",acceptConnection);peer.on("error",error=>{if(error.type==="unavailable-id"||error.type==="peer-unavailable"){try{peer.destroy()}catch{}migrationTimer=setTimeout(claim,1200)}else{migrationInProgress=false;status(`Migrarea gazdei a eșuat: ${error.type}`,true)}})};migrationTimer=setTimeout(claim,500)}
function playerById(id){return onlineState.players.find(player=>player.id===id)}
function next(id){let players=onlineState.players,start=players.findIndex(player=>player.id===id);for(let n=1;n<=players.length;n++){let player=players[(start+n)%players.length];if(!player.out)return player.id}return id}
function onlineTurnPlayerId(s=onlineState){return s.phase==="defend"?s.defender:s.phase==="attackBatch"?s.batchPlayer:s.attacker}
function scheduleOnlineTurnTimeout(){clearTimeout(onlineTurnTimer);onlineTurnTimer=null;if(window.__DURAK_DISABLE_TURN_TIMER||!isHost||!onlineState?.players||onlineState.over||onlineState.opening){if(onlineState?.players)delete onlineState.turnDeadline;return}onlineState.turnDeadline=Date.now()+TURN_TIMEOUT_MS;onlineTurnTimer=setTimeout(autoPlayTimedOutTurn,TURN_TIMEOUT_MS)}
function autoPlayTimedOutTurn(){onlineTurnTimer=null;let s=onlineState;if(!isHost||!s?.players||s.over||s.opening)return;let playerId=onlineTurnPlayerId(s),p=playerById(playerId),action=null;if(!p||p.out)return;if(s.phase==="attack"){let card=[...p.hand].sort((a,b)=>rank(a)-rank(b))[0];if(card)action={type:"card",id:card.id}}else if(s.phase==="attackBatch")action={type:"sendBatch"};else if(s.phase==="defend"){let open=s.battle.find(pair=>!pair.defense),card=open?[...p.hand].filter(item=>beatsOnline(item,open.attack)).sort((a,b)=>rank(a)-rank(b))[0]:null;action=card?{type:"card",id:card.id}:{type:"take"}}else if(s.phase==="add")action={type:"finish"};else if(s.phase==="taking")action={type:"finishTake"};if(action)processAction(playerId,action)}
function showOnlineTurnClock(s){clearTimeout(turnClockTimer);turnClockTimer=null;let box=ui("turnTimer");if(!Number.isFinite(s?.turnDeadline)||s.opening||s.over){box.hidden=true;return}let tick=()=>{let seconds=Math.max(0,Math.ceil((s.turnDeadline-Date.now())/1000));box.hidden=false;box.textContent=`⏱ ${seconds}s`;box.className=`turn-timer${seconds<=10?" urgent":""}`;if(seconds>0)turnClockTimer=setTimeout(tick,250)};tick()}
function onlineTableRanks(s=onlineState){return new Set(s.battle.flatMap(pair=>[pair.attack.rank,pair.defense?.rank].filter(Boolean)))}
function canJoinOnlineAttack(s,p,c){return !!p&&!p.out&&p.id!==s.defender&&s.battle.length<s.limit&&onlineTableRanks(s).has(c.rank)}
function onlinePlayableCardIds(s,p){if(!p||p.out||s.over)return null;if(s.phase==="attack"&&p.id===s.attacker)return new Set(s.battle.length<s.limit?p.hand.map(c=>c.id):[]);if(s.phase==="attackBatch"&&p.id===s.batchPlayer)return new Set(s.battle.length<s.limit?p.hand.filter(c=>c.rank===s.battle[0]?.attack.rank).map(c=>c.id):[]);if((s.phase==="add"||s.phase==="taking")&&p.id!==s.defender){let ranks=onlineTableRanks(s);return new Set(s.battle.length<s.limit?p.hand.filter(c=>ranks.has(c.rank)).map(c=>c.id):[])}if(s.phase==="defend"&&p.id===s.defender){let open=s.battle.find(pair=>!pair.defense);return new Set(p.hand.filter(c=>open&&beatsOnline(c,open.attack)).map(c=>c.id))}return null}
function onlineCardClass(card,playable){return `player-card${playable?playable.has(card.id)?" playable-card":" not-playable-card":""}`}
function refillOnline(){let s=onlineState,attacker=playerById(s.attacker),defender=playerById(s.defender),order=[attacker,...s.players.filter(p=>p.id!==s.attacker&&p.id!==s.defender),defender];order.forEach(p=>{if(!p||p.out)return;while(p.hand.length<6&&s.deck.length)p.hand.push(s.deck.pop())});s.players.forEach(p=>{if(!s.deck.length&&!p.hand.length&&!p.out){p.out=true;s.winner.push(p.id)}})}
function newOnlineRound(att){clearTimeout(onlineAttackBatchTimer);let s=onlineState,alive=s.players.filter(p=>!p.out);s.battle=[];delete s.batchPlayer;if(alive.length<=1){s.over=true;if(alive[0]&&!s.winner.includes(alive[0].id))s.winner.push(alive[0].id);return}if(playerById(att)?.out)att=next(att);s.attacker=att;s.defender=next(att);s.limit=Math.min(6,playerById(s.defender).hand.length);s.phase="attack"}
function removeOnlinePlayer(playerId){let s=onlineState,p=playerById(playerId);if(!p||p.left)return;clearTimeout(disconnectTimers.get(playerId));disconnectTimers.delete(playerId);let wasAttacker=playerId===s.attacker,wasDefender=playerId===s.defender,wasBatchPlayer=s.batchPlayer===playerId;p.left=true;p.out=true;p.disconnected=false;p.hand=[];recordOnlineHistory(`${p.name} a ieșit din partidă.`);if(wasAttacker||wasDefender||wasBatchPlayer){clearTimeout(onlineAttackBatchTimer);onlineAttackBatchTimer=null}let alive=s.players.filter(player=>!player.out);if(alive.length<=1){s.battle=[];delete s.batchPlayer;s.over=true;if(alive[0]&&!s.winner.includes(alive[0].id))s.winner.push(alive[0].id)}else if(wasAttacker||wasDefender){let newAttacker=wasAttacker?next(playerId):s.attacker;newOnlineRound(newAttacker);refillOnline()}else if(s.phase==="attackBatch"&&wasBatchPlayer){s.phase="defend";delete s.batchPlayer}scheduleOnlineTurnTimeout();sync()}
function scheduleOnlineAttackBatch(){clearTimeout(onlineAttackBatchTimer);onlineAttackBatchTimer=null}
function processAction(playerId,a){
  if(!isHost||onlineState.over||onlineState.opening)return;
  let s=onlineState,p=playerById(playerId),reactionKind=null,historyText="",changed=false;if(!p)return;
  if(a.type==="card"){
    let k=p.hand.findIndex(c=>c.id===a.id);if(k<0)return;let c=p.hand[k];
    if(s.phase==="attack"&&playerId===s.attacker){
      if(s.battle.length>=s.limit)return;
      p.hand.splice(k,1);s.battle.push({attack:c});s.phase="attackBatch";s.batchPlayer=playerId;scheduleOnlineAttackBatch();reactionKind="attack";historyText=`${p.name} a atacat cu ${c.rank}${c.suit}.`;changed=true;
    }else if(s.phase==="attackBatch"&&playerId===s.batchPlayer){
      if(s.battle.length>=s.limit)return;
      let hasDefense=s.battle.some(pair=>pair.defense),allowed=hasDefense?onlineTableRanks(s).has(c.rank):c.rank===s.battle[0].attack.rank;if(!allowed)return;
      p.hand.splice(k,1);s.battle.push({attack:c});scheduleOnlineAttackBatch();historyText=`${p.name} a adăugat ${c.rank}${c.suit}.`;changed=true;
    }else if(s.phase==="add"&&canJoinOnlineAttack(s,p,c)){
      p.hand.splice(k,1);s.battle.push({attack:c});s.phase="attackBatch";s.batchPlayer=playerId;scheduleOnlineAttackBatch();reactionKind="attack";historyText=`${p.name} a adăugat ${c.rank}${c.suit}.`;changed=true;
    }else if(s.phase==="taking"&&canJoinOnlineAttack(s,p,c)){
      p.hand.splice(k,1);s.battle.push({attack:c});reactionKind="attack";historyText=`${p.name} a adăugat ${c.rank}${c.suit}.`;changed=true;
    }else if(s.phase==="defend"&&playerId===s.defender){
      let o=s.battle.find(x=>!x.defense);if(!o||!beatsOnline(c,o.attack))return;p.hand.splice(k,1);o.defense=c;s.phase=s.battle.some(pair=>!pair.defense)?"defend":"add";reactionKind="defend";historyText=`${p.name} a apărat cu ${c.rank}${c.suit}.`;changed=true
    }
  }else if(a.type==="sendBatch"&&playerId===s.batchPlayer&&s.phase==="attackBatch"){
    clearTimeout(onlineAttackBatchTimer);onlineAttackBatchTimer=null;s.phase="defend";delete s.batchPlayer;changed=true;
  }else if(a.type==="take"&&playerId===s.defender&&(s.phase==="defend"||s.phase==="add")&&s.battle.length){
    clearTimeout(onlineAttackBatchTimer);onlineAttackBatchTimer=null;s.phase="taking";delete s.batchPlayer;reactionKind="take";historyText=`${p.name} ia cărțile.`;changed=true;
  }else if(a.type==="finishTake"&&playerId===s.attacker&&s.phase==="taking"){
    let d=s.defender;playerById(d).hand.push(...s.battle.flatMap(x=>[x.attack,x.defense].filter(Boolean)));refillOnline();newOnlineRound(next(d));historyText="Cărțile au fost ridicate de pe masă.";changed=true;
  }else if(a.type==="finish"&&playerId===s.attacker&&s.phase==="add"&&!s.battle.some(pair=>!pair.defense)){
    let d=s.defender;refillOnline();newOnlineRound(d);reactionKind="finish";historyText="Atacul s-a încheiat cu apărare.";changed=true;
  }
  if(!changed)return;
  if(historyText)recordOnlineHistory(historyText);
  if(reactionKind)reactOnline(playerId,reactionKind);
  scheduleOnlineTurnTimeout();
  sync();
}
function allowLocalAction(now=Date.now()){localActionTimes=localActionTimes.filter(time=>now-time<ACTION_RATE_WINDOW_MS);if(localActionTimes.length>=ACTION_RATE_MAX){showAntiSpam();return false}localActionTimes.push(now);return true}
function act(a){if(onlineState?.opening||onlineOpeningVisual?.running||!allowLocalAction())return;if(isHost)processAction(myPlayerId,a);else send(connections[0],{type:"action",action:a})}
function sendOnlineEmote(kind){if(!onlineActive||onlineState?.opening||!new Set(["think","attack","laugh","angry"]).has(kind))return;let now=Date.now();if(now-localEmoteAt<4000)return showAntiSpam("Reacțiile au pauză 4 secunde.");localEmoteAt=now;if(isHost){reactOnline(myPlayerId,kind);sync()}else send(connections[0],{type:"emote",kind})}
document.querySelectorAll("[data-emote]").forEach(button=>button.addEventListener("click",()=>{if(document.body.classList.contains("online-active"))sendOnlineEmote(button.dataset.emote)}));
function reactionPlayer(p,reaction){return reaction?.playerId===p.id?{...p,openingEmotion:reaction.emotion,openingLine:reaction.phrase,forceDialogue:true}:p}
function renderOnline(){
  let s=isHost&&onlineState?.players?window.DurakMultiplayerSession.viewForPlayer(onlineState,myPlayerId):onlineState;
  if(!s?.players)return;
  if(s.opening){if(!onlineOpeningVisual||onlineOpeningVisual.id!==s.opening.id)runOnlineOpening(s);renderOnlineOpeningFrame(s);return}
  showOnlineTurnClock(s);
  let history=ui("historyList");if(history){history.innerHTML=(s.history||[]).slice(-6).map(item=>`<div class="history-entry">${escapeOnlineHtml(item.text||item)}</div>`).join("");ui("moveHistory").hidden=false}
  let reaction=s.reaction&&s.reaction.expiresAt>Date.now()?s.reaction:null;
  clearTimeout(reactionViewTimer);
  if(reaction)reactionViewTimer=setTimeout(renderOnline,Math.max(0,reaction.expiresAt-Date.now()+30));
  let me=s.players.find(p=>p.id===myPlayerId);
  if(!me?.hand)return;
  let visiblePlayers=s.players.filter(p=>!p.left),others=visiblePlayers.filter(p=>p.id!==me.id),seats=window.DurakRoundTable.createTableLayout(visiblePlayers.map(p=>p.id),me.id),seatById=new Map(seats.map(x=>[x.playerId,x])),turnPlayerId=onlineTurnPlayerId(s),selfReaction=reaction?.playerId===me.id?reaction:null,badge=ui("playerReaction");
  badge.textContent=selfReaction?.phrase||"";
  badge.className=`player-reaction ${selfReaction?.emotion||""}`;
  ui("opponents").innerHTML=others.map(p=>{let count=p.handCount??p.hand?.length??0;return `<article data-player-id="${p.id}" style="${window.DurakRoundTable.seatStyle(seatById.get(p.id))}" class="bot-seat arrival-ready ${p.out?"out":""} ${p.disconnected?"disconnected":""} ${p.id===s.attacker?"attacker":""} ${s.battle.length&&p.id===s.defender?"defender":""} ${p.id===turnPlayerId?"active-turn":""}">${window.DurakAvatarArrival.chairHTML()}${avatarHTML(reactionPlayer(p,reaction))}<div class="bot-info"><strong>${escapeOnlineHtml(p.name)}</strong><span>${p.disconnected?"reconectare…":p.out?"a terminat":count+" cărți"}</span></div><div class="hand bot-hand">${Array.from({length:count},()=>botCardHTML()).join("")}</div></article>`}).join("");
  document.querySelector(".you").style.cssText=window.DurakRoundTable.seatStyle(seatById.get(me.id));
  document.querySelector(".you").classList.toggle("active-turn",me.id===turnPlayerId);
  let playable=onlinePlayableCardIds(s,me);
  ui("playerHand").innerHTML=[...me.hand].sort((a,b)=>rank(a)-rank(b)).map(c=>cardHTML(c,onlineCardClass(c,playable))).join("");
  ui("playerCount").textContent=`${me.hand.length} cărți`;
  let deckCount=s.deckCount??s.deck?.length??0,trumpCard=s.trumpCard??s.deck?.[0];
  ui("deckCount").textContent=deckCount;
  ui("deck").style.display=deckCount?"block":"none";
  ui("trump").innerHTML=deckCount&&trumpCard?cardHTML(trumpCard):`<b style="font-size:35px">${s.trump}</b>`;
  ui("battlefield").innerHTML=s.battle.length?s.battle.map(x=>`<div class="pair">${cardHTML(x.attack)}${x.defense?cardHTML(x.defense,"defense"):""}</div>`).join(""):`<div class="empty-table">Masa este liberă</div>`;
  document.querySelectorAll(".player-card").forEach(e=>e.onclick=()=>act({type:"card",id:e.dataset.id}));
  let action="",fn=null,msg="",defender=s.players.find(p=>p.id===s.defender),actorId=s.phase==="defend"?s.defender:s.phase==="attackBatch"?s.batchPlayer:s.attacker,actor=s.players.find(p=>p.id===actorId)||defender;
  if(s.over){let order=[...s.winner.map(id=>s.players.find(p=>p.id===id)).filter(Boolean),...s.players.filter(p=>!s.winner.includes(p.id))],place=order.findIndex(p=>p.id===myPlayerId)+1;if(place>0)window.DurakProfile?.recordResult?.(s.gameId,place,order.length);ui("resultTitle").textContent="Clasament multiplayer";ui("resultText").textContent="Partida s-a terminat. Monedele au fost adăugate în profil.";ui("podium").innerHTML=order.slice(0,3).map((p,i)=>`<div class="podium-player place-${i+1}">${avatarHTML(reactionPlayer({...p,openingEmotion:i===0?"laughing":i===2?"angry":""},null))}<b>${escapeOnlineHtml(p.name)}</b><span>${i+1}</span></div>`).join("");ui("standings").innerHTML=order.map((p,i)=>`<div class="standing-row ${i===0?"winner":""} ${i===order.length-1?"durak":""}"><span class="medal">${i<3?["🥇","🥈","🥉"][i]:"•"}</span><b>${escapeOnlineHtml(p.name)}</b><span>${i===order.length-1?"DURAK":`LOCUL ${i+1}`}</span></div>`).join("");ui("modal").hidden=false;msg="Partida s-a terminat."}
  else if(s.phase==="defend"&&myPlayerId===s.defender){msg="Ești atacat. Bate cartea sau ia masa.";action="Ia cărțile";fn=()=>act({type:"take"})}
  else if(s.phase==="attackBatch"&&myPlayerId===s.batchPlayer){msg="Mai poți pune rapid cărți permise sau poți trimite lotul.";action="Trimite atacul";fn=()=>act({type:"sendBatch"})}
  else if(s.phase==="attack"&&myPlayerId===s.attacker){msg=`Atacă-l pe ${defender.name}.`}
  else if(s.phase==="add"&&myPlayerId!==s.defender&&!me.out){msg="Poți adăuga orice valoare aflată deja pe masă.";if(myPlayerId===s.attacker){action="Gata";fn=()=>act({type:"finish"})}}
  else if(s.phase==="taking"&&myPlayerId!==s.defender&&!me.out){msg=`${defender.name} ia cărțile. Mai poți adăuga o valoare de pe masă.`;if(myPlayerId===s.attacker){action="Gata, să le ia";fn=()=>act({type:"finishTake"})}}
  else if(s.phase==="taking"&&myPlayerId===s.defender)msg="Ai spus că iei. Așteaptă până ceilalți termină de adăugat.";
  else msg=`Așteaptă mutarea lui ${actor?.name||"altui jucător"}.`;
  setStatus(msg,action,fn)
}
ui("newGame").onclick=()=>{cleanPeer();over=true;ui("skipBtn").hidden=true;ui("mainMenu").hidden=false;ui("setup").hidden=true;ui("onlineLobby").hidden=true};
const singlePlayAgain=ui("playAgain").onclick;
ui("playAgain").onclick=()=>{if(!onlineActive)return singlePlayAgain?.();cleanPeer();ui("modal").hidden=true;ui("mainMenu").hidden=false;ui("setup").hidden=true;ui("onlineLobby").hidden=true};
})();
